[tool.poetry]
name = "smartrepo"
version = "0.1.0"
description = "A powerful repository module finder"
authors = ["Igdálias Cabamba <igdaliasmussulveiracabamba@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
clean-text = "^0.6.0"
klein = "^21.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
